spring:
  application:
    name: hello-spring-boot
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8088
  servlet:
    context-path: /boot

logging:
  level.org.springframework.web: DEBUG
  file:
    name: ../logs/spring-boot-hello.log
 